services:
  humble-superhero:
    image: humble-superhero
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION} # 22.13.1
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
          ignore:
            - node_modules
        - path: ./package.json
          target: /app/package.json
          action: rebuild
