services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22.13.1 # 22.13.1
    env_file:
      - .env.local
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
          ignore:
            - node_modules
        - path: ./package.json
          target: /app/package.json
          action: rebuild

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22.13.1 # 22.13.1
    env_file:
      - .env.local
    ports:
    - "5173:80"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
